<?php

namespace Vipa\ImportBundle\Helper;

class FileHelper
{
    public static $mimeToExtMap = [
        ''                                                                          => 'unknown',
        'application/pdf'                                                           => 'pdf',
        'image/jpeg'                                                                => 'jpg',
        'image/pjpeg'                                                               => 'jpg',
        'image/png'                                                                 => 'png',
        'image/bmp'                                                                 => 'bmp',
        'image/gif'                                                                 => 'gif',
        'image/tiff'                                                                => 'tiff',
        'image/x-ms-bmp'                                                            => 'bmp',
        'image/x-png'                                                               => 'png',
        'octet/stream'                                                              => 'bin',
        'text/html'                                                                 => 'html',
        'text/richtext'                                                             => 'rtf',
        'text/rtf'                                                                  => 'rtf',
        'text/x-asm'                                                                => 'asm',
        'text/x-c'                                                                  => 'c',
        'text/x-c++'                                                                => 'cpp',
        'text/x-php'                                                                => 'php',
        'text/xml'                                                                  => 'xml',
        'video/mp4'                                                                 => 'mp4',
        'application/msword'                                                        => 'doc',
        'application/zip'                                                           => 'zip',
        'application/xml'                                                           => 'xml',
        'text/plain'                                                                => 'txt',
        'text/x-tex'                                                                => 'tex',
        'application/rar '                                                          => 'rar',
        'application/x-rar'                                                         => 'rar',
        'application/tiff'                                                          => 'tiff',
        'application/x-font-ttf'                                                    => 'ttf',
        'application/octet-stream'                                                  => 'bin',
        'application/text-plain:formatted'                                          => 'txt',
        'application/doc'                                                           => 'doc',
        'application/docx'                                                          => 'docx',
        'application/jar'                                                           => 'jar',
        'application/mathematica'                                                   => 'm',
        'application/octect-stream'                                                 => 'bin',
        'application/octetstream'                                                   => 'bin',
        'application/rar'                                                           => 'rar',
        'application/rtf'                                                           => 'rtf',
        'application/vnd.ms-office'                                                 => 'doc',
        'application/vnd.ms-excel'                                                  => 'xls',
        'application/vnd.ms-powerpoint'                                             => 'ppt',
        'application/vnd.ms-word'                                                   => 'doc',
        'application/vnd.ms-word.document.12'                                       => 'doc',
        'application/vnd.ms-word.document.macroEnabled.12'                          => 'doc',
        'application/vnd.oasis.opendocument.presentation'                           => 'odp',
        'application/vnd.oasis.opendocument.text'                                   => 'odt',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document'   => 'docx',
        'application/vnd.openxmlformats-officedocument.presentationml.presentation' => 'pptx',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'         => 'xlsx',
        'application/x-7z-compressed'                                               => '7z',
        'application/x-rar-compressed'                                              => 'rar',
        'application/x-tex'                                                         => 'tex',
        'application/x-zip'                                                         => 'zip',
        'application/x-zip-compressed'                                              => 'zip',
    ];
}
