<?php

namespace OkulBilisim\OjsImportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PendingStatisticImportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PendingStatisticImportRepository extends EntityRepository
{
}
