<?php

namespace OkulBilisim\OjsImportBundle\Entity;

/**
 * PendingStatisticImportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PendingStatisticImportRepository extends \Doctrine\ORM\EntityRepository
{
}
